### ISSUE TITLE
Program fails under some inputs.

### ISSUE THREAD

**Issue by Tushar-Harsora** [r4hu1s0n7/HelloDB#1]
I am running using `dotnet run`

EXPECTED OUTPUT
```
command > She chose an elective course in photography to explore her creative side
Unrecognised Command
command > The school has a selective admissions process, accepting only the top applicants
Unrecognised Command
```

ACTUAL OUTPUT
```
command > She chose an elective course in photography to explore her creative side
Unrecognised Command
command > The school has a selective admissions process, accepting only the top applicants
Unhandled exception. System.FormatException: The input string 'hool' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Convert.ToInt32(String value)
   at QueryExecution.<>c.<Execute>b__0_0(String i) in /Users/69696969/development/dotnet/HelloDB/Hello/QueryExecution.cs:line 15
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at QueryExecution.Execute(QueryStatement queryStatement, String input) in /Users/69696969/development/dotnet/HelloDB/Hello/QueryExecution.cs:line 15
   at Program.Main(String[] args) in /Users/69696969/development/dotnet/HelloDB/Hello/Program.cs:line 37
```

**Comment by Tushar-Harsora** [comment]
It also fails when keeping input empty. just pressing enter. 

```
command > 
Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.String.get_Chars(Int32 index)
   at Program.Main(String[] args) in /Users/69696969/development/dotnet/HelloDB/Hello/Program.cs:line 11
```

**Comment by r4hu1s0n7** [comment]
thanks for pointing out, will fix it by next release

**Comment by r4hu1s0n7** [comment]
Hey @Tushar-Harsora its fixed!
